### ISSUE TITLE
Isoler les formulaires PAIR

### ISSUE THREAD

**Issue by GuillaumeAV** [jmvanel/semantic_forms#102]
Dans le menu déroulant de création, isoler les formulaires pairs des ontologies existantes ... Et classer les sous-classes au regard de leur classe ;-)

**Comment by jmvanel** [comment]
Il sera toujours possible d'écrire des UI spécialisées,
voir les manuels
https://github.com/jmvanel/semantic_forms/wiki/Application-development-manual
https://github.com/jmvanel/semantic_forms/wiki/Developer_manual
