### ISSUE TITLE
VSI

### ISSUE THREAD

**Issue by happy-dev** [jmvanel/semantic_forms#109]
Bonjour Jean Marc, 

Nous avons des problèmes sur VSI qui nécessitent ton intervention. 
Pourrais-tu me rappeler quand tu as ce message ? 

Belle semaine à toi. 

Alex - 06 51 71 08 21

**Comment by sylvainlb** [comment]
Salut Jean-Marc, tu pourras nous dire si tu as pu avancer et quand tu pourras livrer ?
Merci
