### ISSUE TITLE
Record who did what

### ISSUE THREAD

**Issue by balessan** [jmvanel/semantic_forms#12]
A solution is to use a named graph for each user

**Comment by jmvanel** [comment]
In project jmvanel/corporate_risk@33d3b1425a3921238fd85922faff6cfd34ca9696 , there is a login and user data is saved in a named graph for each user, and with commit https://github.com/jmvanel/semantic_forms/commit/b505b0b002aeacfca0778084c2c80b3dd3117bf1 the form save is adapted to this.

However, the user management should be moved to semantic_forms , or made more reusable.

**Comment by sylvainlb** [comment]
I'm thinking maybe it should be a second library, independent from the forms
