### ISSUE TITLE
 Sparql Exception

### ISSUE THREAD

**Issue by cybercandyman** [jmvanel/semantic_forms#121]
An empty result of a sparql request on /sparql cause the following exception :

![capture d ecran - 11012017 - 09 35 01](https://cloud.githubusercontent.com/assets/2477112/21841155/44f41d26-d7e1-11e6-87d3-9d0780d6ba13.png)

**Comment by jmvanel** [comment]
I couldn't reproduce the problem on the latest code:

SELECT
http://localhost:9000/sparql?query=SELECT%20*%20WHERE%20{%20GRAPH%20?G%20{?S%20%3Curn:blabla%3E%20?O%20.%20}%20}%20LIMIT%204

CONSTRUCT
http://localhost:9000/sparql?query=CONSTRUCT+%7B+%3FS+%3FP+%3FO+.+%7D+WHERE+%7B+GRAPH+%3FG+%7B+%3FS+%3Curn%3Ablabla%3E+%3FO+.+%7D+%7D+LIMIT+10

PLEASE: in a bug report, always indicate:
- how to reproduce the issue

and if necessary:
- what is the expected result
- what is the actual result

**Comment by cybercandyman** [comment]
Issue is solved by updating code to the last version.
An empty result now returns :
"Empty result"

Thanks, 
Regards
