### ISSUE TITLE
bootstrap JS library is downloaded from Internet

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#14]
As a consequence,
when doing a demonstration on localhost,
and internet is slow or not accessible,
the application becomes slow,
because there is a timeout and 
the bootstrap JS library is not found from Internet.

The bootstrap JS library should be copied in 
scala/forms_play/public/javascripts

**Comment by jmvanel** [comment]
Sylvain,
can we close this issue ?

**Comment by balessan** [comment]
Fixed some time ago.
