### ISSUE TITLE
URL decode pour la création de compte par email

### ISSUE THREAD

**Issue by SebLemoine** [jmvanel/semantic_forms#148]
Si l'on créer un compte avec un email : pour se connecter par la suite, il faut utiliser l'email encodé.

exemple : 
je créer un compte avec comme login test@test.fr
pour me connecter le lendemain, le login test@test.fr ne fonctionneras pas -> il faut utiliser test%40test.fr

**Comment by jmvanel** [comment]
FIXED by https://github.com/jmvanel/semantic_forms/commit/82bc895c228b8890dae356e7898330752507d869
