### ISSUE TITLE
enhance the UI for selecting an URI resource: use completion

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#15]
- show the label associated to each URI instead of the URI
- completion on the label

**Comment by jmvanel** [comment]
The label associated to each URI is shown by a <datalist> HTML tag.

**Comment by sylvainlb** [comment]
Select2 is probably a good option.

**Comment by jmvanel** [comment]
You mean http://select2.github.io/  ?

**Comment by sylvainlb** [comment]
Yes, I guess it covers the need.

**Comment by jmvanel** [comment]
I gusess Select2 could also be used for #2 ; see here :
https://github.com/jmvanel/semantic_forms/blob/master/scala/forms_play/public/javascripts/wikipedia.js#L22

**Comment by jmvanel** [comment]
Wouldn't a short piece of plain JavaScript do the job of showing and complete on label, and sending URI to form ? see :
http://stackoverflow.com/questions/18464479/can-html5-datalist-differentiate-value-and-option-text

**Comment by sylvainlb** [comment]
Yes but it would be simpler and better made with Select2

**Comment by jmvanel** [comment]
Currently it works with a an &lt;input> tag and and the &lt;datalist is updated by wikipedia.js ,
but the pulldown menu is not automatically shown .

**Comment by jmvanel** [comment]
Try to use the new /lookup service , with the new completion widget mentionned in #2 .
