### ISSUE TITLE
datatype validation : integer

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#16]
This is to be implemented  by JavaScript ( or Scala.JS ).
Later we will need date, telephone, ...

**Comment by sylvainlb** [comment]
We probably need to do it for boolean too?

**Comment by jmvanel** [comment]
Sure, boolean, float, and integer ( with interval ) are the ones that don't need a special UI component ,contrary to date, telephone.

**Comment by sylvainlb** [comment]
For the date, I suggest we use the bootstrap datepicker which is very good, as we already embedded bootstrap.
The telephone is trickier as it needs specific development and we don't want to be too restrictive. Depending on countries, the way of writing phone numbers can be very diverse.

**Comment by jmvanel** [comment]
Do it , please ! :)
I assume that the bootstrap datepicker is able to spit a date in XML Schema format .

**Comment by sylvainlb** [comment]
I'm adding a client side validation, but we also need a server side validation, and maybe 2: one during the form construction from the request, in order to let application handle validation errors, and one in the save, to make sure the data stored is consistent.

**Comment by jmvanel** [comment]
Right , Sylvain !

**Comment by jmvanel** [comment]
HTML5 datatype validation is working and good enough => issue closed
