### ISSUE TITLE
Foster links between data

### ISSUE THREAD

**Issue by GuillaumeAV** [jmvanel/semantic_forms#160]
I've created a reference to a SOLID presentation as a foaf:document : http://semantic-forms.cc:9112/display?displayuri=https%3A%2F%2Fsolid.github.io%2Fintro-to-solid-slides%2F%2324

Then I've created a primary topic for this doc (SOLID) ... 
http://semantic-forms.cc:9112/display?displayuri=http%3A%2F%2Fsemantic-forms.cc%3A9112%2Fldp%2FSOLID_%2528Social_Linked_Data%2529

When I search SOLID, I don't find the SOLID presentation ... 

A retrolink should exist between these 2 data ..

**Comment by jmvanel** [comment]
This search works fine
http://semantic-forms.cc:9112/wordsearch?q=Solid&clas=

And this URI
http://semantic-forms.cc:9112/display?displayuri=https%3A%2F%2Fsolid.github.io%2Fintro-to-solid-slides%2F%2324
indeed *has* a link http://xmlns.com/foaf/0.1/primaryTopic to 
http://semantic-forms.cc:9112/display?displayuri=http%3A%2F%2Fsemantic-forms.cc%3A9112%2Fldp%2FSOLID_%2528Social_Linked_Data%2529

**Comment by jmvanel** [comment]
Guillaume, if this is still bad , you can re-open the issue :) .
