### ISSUE TITLE
SPARQL query and wget script for moving data to another named graph

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#165]
use case: moving data
```turtle
<S> ?P ?O .
```
from a named graph to another;
typically for moving a FOAF profile typed by the wrong user.

**Comment by SebLemoine** [comment]
query : 
```turtle
DELETE { GRAPH <oldGraph> { <S> ?P ?O }} INSERT{ GRAPH <newGraph> { <S> ?P ?O }} WHERE {GRAPH <oldGraph> { <S> ?P ?O}}
```

**Comment by jmvanel** [comment]
OK , after thinking more,
replace <S> by ?S

Put this in a script
dist/scripts/rgraphmove.sh
like
dist/scripts/rgraphremove.sh

**Comment by SebLemoine** [comment]
you need to have <S> to be sure to move the good content, imagin if you have more than 1 content in the graph, you need to precise the subject

**Comment by SebLemoine** [comment]
I have done a script who the suject is objtionnal
