### ISSUE TITLE
Triples from LOD should not be editable

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#166]
Such triples indeed are are not modifiable in the semantic cache.
Same thing for triples from other users.

**Comment by SebLemoine** [comment]
It's done but problem in save. He rewrite the author oh all triplet

**Comment by jmvanel** [comment]
@SebLemoine , which commits did you do ?
I don't see nothing changed in .eg.
http://localhost:9000/edit?url=http%3A%2F%2Fdbpedia.org%2Fresource%2FLoquat

**Comment by SebLemoine** [comment]
see cmmit : 2d0e374d60db77ac789380a9168fc7089245af7b
We have done the 1rst steps, let only editable the triple who we are the author ( or the triplet who we are nor the authoer) . We have , maybe, to upgrade what we have done to check if the data is preset

**Comment by SebLemoine** [comment]
with the commit : 3f2ac6b85c79ff6e181a55d07806b9e08a1a3829
Now the clone work for all fields. 
The last things now is when we save, all triplet do not become "anonymous" but became under the user.
This problem is when we save metadata about triplet

**Comment by jmvanel** [comment]
Now the foreign triples (from Internet or from other users) are not editable in UI;
to add to the subject - property pair, the "+" button must be used.
