### ISSUE TITLE
Controle d'accès sur sémantique forms ( exemple de celui des Grands Voisins )

### ISSUE THREAD

**Issue by SebLemoine** [jmvanel/semantic_forms#168]
( quand je parle de composant, je parle des classes (projet, event, proposition, organisation et personne )
les rôles sont en cascade, càd qu'il hérite des précédents

## Rôle anonyme ( non connecté ) :
- back : 
  - pas accès
- front : 
  - peut se balader librement
  - vue détail : filtrage de certain champs dans les composants

## Rôle member :
- back :
  - peut renseigner son profil
- front :
  - peut se balader librement
  - vue détail : aucun filtrage des champs dans les composants sauf pour organisation

## Rôle admin :
- back :
   - peut renseigner l'organisation mais pas tous les champs
   - peut accéder à une vue contenant l’ensemble des membres de l'organisation et leur droit
   - peut ajouter/modifier/supprimer des projets, events, propositions
- front :
  - pas plus que member

## Rôle Super_Admin :
- back :
  - peut accéder a vue d’ensemble des organisations présente sur le site ( présente sur mysql )
  - peut éditer toutes les organisations présentes
- front :
  - sur la vue de détail d'une organisation, voit tous les champs

## Notre base sql contient
- table user :
   - login
   - mot de passe
   - email
   - compte autorisé (enabled)
   - mot de passe
   - date de dernière co
   - rôle
   - lien du profil sf
   - FK_orga
   - nom du fichier image du profil
- table orga :
   - nom ( peut être retiré)
   - lien du profil orga sf
   - FK responsable
   - nom du graph
   - nom du fichier image du profil orga

**Comment by jmvanel** [comment]
Choix de solutions
1. utiliser l'API Jena (permet un contrôle total en lecture et écriture à travers tous les accès: SPARQL, API)
2. utiliser graphes nommés et database distinctes, voir issue "Access control" #155

Dans le cas 2 , l'implémentation ne consiste pas à protéger la donnée , mais à l'afficher conjointement avec la donnée publique ("multiplexage") .

**Comment by jmvanel** [comment]
mail 29 mai "Notes et plans pour SF: réseau social , Contrôle d'accès"

Contrôle d'accès

Sécurité modérée : 
Données publiques mais en édition partagée
On crée un graphe nommé pour cette collaboration, ensuite on édite un URI sujet ( uri= ) dans ce graphe nommé  ( graph= ).
Celui qui a l'URI peut y accéder; on affichera des liens vers les graphes nommés éditables par l'utilisateur.

Données privées
A AFFINER

    Utilisation de database= pour utiliser des database distinctes
    on peut fusionner le sous graphe public avec
    le sous graphe privé via union dans Banana-RDF


Personnelles
A SUIVRE
Partagées
A SUIVRE

**Comment by jmvanel** [comment]
Si quelqu'un veut implémenter cela, je l'aiderai :)
Mais le choix depuis le départ est le LOD, pas les données privées.
Par contre un fonctionnement en CMS classique est envisagé.
