### ISSUE TITLE
CSS classes configurable via RDF

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#30]
Currently CSS classes for labels and fields are hard coded;
they should be configurable via RDF in the database.

HTML generation occurs in Forms2HTML .

**Comment by jmvanel** [comment]
After reflexion,
the important point is that the CSS should be configurable *somehow* ,
not necessarily in the RDF database.

**Comment by balessan** [comment]
It is configurable for now through the Configuration class, right ?
Considering closing this issue ?

**Comment by balessan** [comment]
Close because it has been fixed.
