### ISSUE TITLE
add Play login & Authentification

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#33]
borrow from https://github.com/deductions/corporate_risk ,
but use semantic_forms forms.

**Comment by jmvanel** [comment]
See also Simple secure multi-user management #3 .

The behavior that we want for a public site for a first implementtion is:

1. still allow read only pages to non-authenticated users
1. only allow access to data modification to authenticated users
1. in non-authenticated mode, add a sign-in button to a page about a foaf:Person or sub-class or maybe schema.org Person, or even Organization or Project;
this will allow a user to claim the FOAF identify corresponding to the current page, and avoid to type again the name and email ( for a user already having a public FOAF page, she can upload it to semantic_form by pasting the URI in the "display URI" field ) 
1. in non-authenticated mode, add a login button in every page
1. in authenticated mode, show the login name in every page

**Comment by balessan** [comment]
Closed ? The login and authentication has been integrated, even if it has been done in a simple way we could improve.
