### ISSUE TITLE
Automatic form: add rdfs:label and rdfs:comment

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#44]
Systematically add rdfs:label and rdfs:comment when there is no form specification .

**Comment by moissinac** [comment]
The form seems to wait for an URI for comment and label and convert automatically to an URI any text entered in the field. For me, label end comment are text only, potentially with language information

**Comment by jmvanel** [comment]
Can you paste the URL that you try,
and anything necessary to reproduce the issue ?

On my development machine ( Ubuntu 16.04, Firefox 49.0.2, Java openjdk version "1.8.0_111" )
Creating for example an instance of a non-"existing" class blbla/blibli : 

http://localhost:9000/create?uri=blbla%3Ablibli

works perfectly: after saving, label and comment are literals not URI's .

The reason I can think of is the following:
the RDFS vocabulary is not loaded.

To fix that, either:
- load all usual ontologies, see end of paragraph https://github.com/jmvanel/semantic_forms/blob/master/doc/fr/install.md#d%C3%A9marrer-lapplication-zipp%C3%A9e ( same parag. in english nearby )
- just load  <http://www.w3.org/2000/01/rdf-schema#>

**Comment by moissinac** [comment]
Just creating a foaf:Person, resulting in the url
http://127.0.0.1:9000/create?uri=&uri=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FPerson
The grey text in the label field is
Entrer ou coller une ressource (URI) de type (); saisir ici crée une nouvelle ressource; mieux vaut...
Same in the comment field
The list of fields seems to be the good one, with some fields with the grey text:
Enter or paste a string

**Comment by jmvanel** [comment]
Did you run PopulateRDFCache, like recommended in  paragraph https://github.com/jmvanel/semantic_forms/blob/master/doc/fr/install.md#d%C3%A9marrer-lapplication-zipp%C3%A9e ?

**Comment by jmvanel** [comment]
A verification that you can do is type rdfs:label in "Afficher" ;
you should see this : 
http://163.172.179.125:9111/display?displayuri=rdfs%3Alabel&Display=Afficher

**Comment by moissinac** [comment]
Result of 'afficher' on rdfs:label
16 subjects, 87 triples, 6 predicates, 39 objects, 6 objects from page URI, type rdf:Property

range Literal     
label
label
isDefinedBy rdf-schema#    
domain Resource 
comment
A human-readable name for the subject.
type 22-rdf-syntax-ns#Property
-- owl#AnnotationProperty

which is a bit different from the same test in the sandbox, but seems acceptable

**Comment by jmvanel** [comment]
OK, so unless contrary clue, another Windows-specific trouble that Romain will investigate tomorrow.

It is the same with all classes ?
You could try creating foaf:Project, schema:AggregateOffer , skos:Concept ...

Did you run PopulateRDFCache ?

**Comment by moissinac** [comment]
The document says
"L'application générique est parfaitement utilisable telle quelle, voir User manual. "
So as the script
scripts/populateRDFCache.sh
seems to be be a shell script for Unix, I didn't try to run it.
