### ISSUE TITLE
Error on fresh install when trying to run the app

### ISSUE THREAD

**Issue by balessan** [jmvanel/semantic_forms#47]
I cannot get semantic_forms to work on a new machine, because after having cloned the repository plus the banana-rdf associated one (and executed the publishLocal on banana-rdf), I only get the following information from the 'run' command execution:

[semantic_forms_play] $ run
[info] Compiling 70 Scala sources to /home/balessan/workspace/semantic_forms/scala/forms/target/scala-2.11/classes...
[error] File name too long
[error] one error found
[error] ({file:/home/balessan/workspace/semantic_forms/scala/forms/}forms/compile:compileIncremental) Compilation failed
[error] Total time: 7 s, completed 9-Nov-2015 6:37:36 PM

Do you have any idea what's going on based on that ? I am kind of stuck...

**Comment by balessan** [comment]
Just moved my /home/balessan/workspace under /workspace/ and get it to work !
As it is said in the error message, 'File name too long'.
I assume the file name was absolute, so it crashed.

**Comment by jmvanel** [comment]
Merci Benoit for reporting !

This seems a generic issue, see here for a remedy :
http://stackoverflow.com/questions/28565837/filename-too-long-sbt

Is your file system an encrypted one (e.g. LUKS) ?

Note that I never put my open source projects in
$HOME/workspace/
but in $HOME/src ,
that shortens a bit the file name,
and my user is just  jmv :) .
