### ISSUE TITLE
Draw a graph for the current resource in page

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#62]
Use Fluidlog:
https://github.com/fluidlog/fluidgraph

There are other tools as well:
https://github.com/jimmccusker/rdfviewer ; see example here :
http://tw.rpi.edu/web/tool/vraer : especially good at showing FOAF profiles : 
http://tw.rpi.edu/web/tool/vraer?url=http://www.w3.org/People/Berners-Lee/card.rdf
http://tw.rpi.edu/web/tool/vraer?url=http://jmvanel.free.fr/jmv.rdf#me

Less good at showing other RDF:
http://tw.rpi.edu/web/tool/vraer?url=http%3A%2F%2Fdbpedia.org%2Fresource%2FBusiness_rule_management_system

NOTE: these URL currently do not work, but downloading the rdfview project and displaying file: URL works.

TimBL's thing : tabulator
https://github.com/linkeddata/tabulator-firefox

**Comment by balessan** [comment]
Closed for now ? As RdfViewer has been integrated ?

**Comment by jmvanel** [comment]
Yes,
closing now;
will open a new issue for enhancing current capabilities of RDFViewer,
under the heading of "diagram".
