### ISSUE TITLE
Use Scala XHTML templates without a special entry in conf/route for each

### ISSUE THREAD

**Issue by jmvanel** [jmvanel/semantic_forms#69]
Currently the Scala XHTML templates are compiled at design time,
and each needs a special entry in conf/route , like /index , /history , etc .

We could use scala compiler at compile time to compile the Scala XHTML templates, much like other Web frameworks do with their brand of templates.
It could even be done at runtime, see
http://stackoverflow.com/questions/23874281/scala-how-to-compile-code-from-an-external-file-at-runtime
http://stackoverflow.com/questions/7477589/compile-and-execute-scala-code-at-runtime

Or maybe better, the Scala XHTML templates will be in the classpath, and some generic route entry similar to the /assets/*file entry will enable all the Scala XHTML templates in some package, say the app/ package .

**Comment by balessan** [comment]
> much like other Web frameworks do with their brand of templates.
Are you talking about other Java Web Frameworks ? Because as far as I know a lot of PHP frameworks are still using routes configuration files.

Seems easier to manage to me to keep a config file than counting on file name.

**Comment by jmvanel** [comment]
The infrastucture is here , see : 
https://github.com/jmvanel/semantic_forms/wiki/Developer_manual#rdf-based-http-controllerrouter

Examples:
http://localhost:9000/page?feature=geoloc:stats
http://localhost:9000/page?feature=dbpedia:Contact_manager
