### ISSUE TITLE
Problem on windows with the zip content

### ISSUE THREAD

**Issue by moissinac** [jmvanel/semantic_forms#70]
When using the batch 
semantic_forms_play.bat
from
https://github.com/jmvanel/semantic_forms/releases/tag/v1.1
I get a message
"La ligne entrée est trop longue"
The message is probably about the line 130 which sets a very big environment variable

**Comment by jmvanel** [comment]
Sorry because I dont have a windows machine at hand currently.
This is a pure Play framework issue, and googling I found this :

https://github.com/playframework/playframework/issues/2025

When using the batch
semantic_forms_play.bat
from
https://github.com/jmvanel/semantic_forms/releases/tag/v1.1
I get a message
"La ligne entrée est trop longue"
The message is probably about the line 130 which sets a very big
environment variable

—
Reply to this email directly or view it on GitHub
<https://github.com/jmvanel/semantic_forms/issues/70>.

**Comment by moissinac** [comment]
So, replacing line 130 by
set "APP_CLASSPATH=%APP_LIB_DIR%\..\conf\;%APP_LIB_DIR%\*;"

works

**Comment by scenaristeur** [comment]
same issue on windows with semantic_forms_play-2.4.
and no script to populate the base like scripts/populateRDFCache.sh ?

C:\Users\Smag\Documents\dev>cd semantic_forms_play-2.4

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4>ls
semantic_forms_play-2.4-SNAPSHOT

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4>cd semantic_forms_play-2.4-SNAPSHOT

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4\semantic_forms_play-2.4-SNAPSHOT>cd bin

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4\semantic_forms_play-2.4-SNAPSHOT\bin>ls
semantic_forms_play  semantic_forms_play.bat

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4\semantic_forms_play-2.4-SNAPSHOT\bin>semantic_forms_play.bat -J-Xmx50M &
La ligne entrée est trop longue.
La syntaxe de la commande n’est pas correcte.
C:\Users\Smag\Documents\dev\semantic_forms_play-2.4\semantic_forms_play-2.4-SNAPSHOT\bin>cd ..

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4\semantic_forms_play-2.4-SNAPSHOT>cd ..

C:\Users\Smag\Documents\dev\semantic_forms_play-2.4>cd ..

C:\Users\Smag\Documents\dev>cd semantic_forms

C:\Users\Smag\Documents\dev\semantic_forms>semantic_forms_play.bat -J-Xmx50M &
'semantic_forms_play.bat' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\Smag\Documents\dev\semantic_forms>cd bin

C:\Users\Smag\Documents\dev\semantic_forms\bin>semantic_forms_play.bat -J-Xmx50M &
La ligne entrée est trop longue.
La syntaxe de la commande n’est pas correcte.
C:\Users\Smag\Documents\dev\semantic_forms\bin>semantic_forms_play.bat -J-Xmx50M
La ligne entrée est trop longue.
La syntaxe de la commande n’est pas correcte.
C:\Users\Smag\Documents\dev\semantic_forms\bin>semantic_forms_play.bat
La ligne entrée est trop longue.
La syntaxe de la commande n’est pas correcte.
