### ISSUE TITLE
Create form for Edit

### ISSUE THREAD

**Issue by simonLouvet** [jmvanel/semantic_forms#79]
Afficher le formulaire de création lors d'une édition pour pourvoir modifier les informations.

Display create form during editon to be able to edit and alter information

**Comment by jmvanel** [comment]
Peux tu coller un URL qui pose problème,
et préciser éventuellement quel est le problème.

Pour moi, le formulaire d'édition est juste  celui de création avec des données déjà présentes; et les mêmes champs sont en premier s'il y a une spécif. de formulaire.
Je viens de tester avec 
http://ldp.virtual-assembly.org:9111/edit?url=http%3A%2F%2Fjmvanel.free.fr%2Fjmv.rdf%23me

et il ne semble pas y avoir de problème , en tous cas pas de régression :) .

**Comment by simonLouvet** [comment]
si on fait "éditer" depuis une url tt va bien effectivement. En fait c'est la visualisation qui pose problème. Quand on fait une recherche on ne peut que visualiser et non éditer.

**Comment by jmvanel** [comment]
Quand on fait une recherche, on accède à la liste des résultats qui chacun renvoie à la page en visualisation, mais chaque page en visualisation a un lien pour éditer ( à côter de la mention "éditer" ,bien sûr )

**Comment by simonLouvet** [comment]
Je pense qu'un bouton éditer serait plus claire que le lien actuel sur l'affichage et que ca devrait être le mode par défaut du lien de recherche. Il ne s'agit que d'ergonomie mais c'est primordiale pour l'adhésion utilisateur. Le mode affichage est trop technique pour les users. Je pense qu'un affichage devrait également passer par le formulaire type édition avec une lecture seule. Le mode affichage technique ne devrait être accessible que pour les user avancés qui veulent rentrer dans la technique. Est il possible que le résultat de la recherche soit un peut plus sexy en tabulaire (je sais que il y a une issue dans ce sens) avec les champs essentiels? Pas un export vers un SpreadSheet mais un affichage html. Merci pour les explications en tout cas.

**Comment by jmvanel** [comment]
Je propose ceci:

- en mode affichage: le libellé n'est plus un lien, et à côté on aura l'icône traditionelle avec un crayon
 - en mode édition: même libellé,  et à côté on aura un bouton pour abandonner l'édition sans sauver, qui renverra au mode affichage

Pour le reste il faut qu'on en parle .

**Comment by jmvanel** [comment]
Bon, après conversation avec Simon, il ressort que :

1. les 3 boutons ?-->o , LINK , et Draw Graph sont jugés trop "techniques" ; il faut donc rendre leur présence configurable
2. le formattage CSS en mode affichage devrait être comme celui en édition

**Comment by balessan** [comment]
En fait il faudrait avoir deux rendering complêtement différents pour les données en visualisation et en édition. À l'heure actuelle on utilise la même fonction pour le rendering, qui est: generateHTMLJustFields (dans Form2HTML.scala). Donc on se retrouve avec les mêmes classes CSSs appliqués sur des éléments de type différents (input versus div). 

Ça ne me semble pas cohérent. Je vais proposer une refonte, en marge du travail sur les boutons !

**Comment by balessan** [comment]
Dans cette issue on mélange pas mal de trucs tout de même, mais:

1. l'affichage des 3 boutons est configurable via le booléen showExpertButtons dans la classe Configuration. Pas compris comment la surcharger dans une application, comme dans Semforms par exemple ?
2. J'ai fais un test de remplacement de ces boutons par des icones. Pas convaincu des icones que j'ai trouvé
3. j'avance ensuite sur la refonte du lien versus le bouton éditer
4. j'avance en parallèle sur le re-formattage du CSS, qui a été impacté par l'ajout d'une classe pour corporate-risk apparemment.

Beaucoup de choses dans cette issue :-)

**Comment by balessan** [comment]
Pas sûr de mon remplacement de: 

    if (shouldAddAddRemoveWidgets(field, editable))
      createHTMLField(field, editable, hrefPrefix, lang)
    else
      // that's for corporate_risk:
       <div class={ css.cssClasses.formInputCSSClass }>
         { createHTMLField(field, editable, hrefPrefix, lang) }
       </div>

par:

    if (shouldAddAddRemoveWidgets(field, editable))
      createHTMLField(field, editable, hrefPrefix, lang)
    else if (editable)
      // that's for corporate_risk:
       <div class={ css.cssClasses.formInputCSSClass }>
         { createHTMLField(field, editable, hrefPrefix, lang) }
       </div>
    else
       createHTMLField(field, editable, hrefPrefix, lang)

Dans le fichier https://github.com/jmvanel/semantic_forms/blob/db01057f2ac18531a81d1c4ef3d7c6ec58b7abbe/scala/forms/src/main/scala/deductions/runtime/html/Form2HTML.scala

Si jamais ça a un impact sur corporate-risk parce que ma logique n'est pas bonne, fais-savoir.

**Comment by jmvanel** [comment]
@balessan tu as demandé 
Le booléen showExpertButtons dans la classe Configuration ;
comment le surcharger dans une application, comme dans Semforms par exemple ?

Faut faire un override dans
semforms/app/controllers/Application.scala

comme c'est fait dans 
https://github.com/jmvanel/corporate_risk/blob/master/app/controllers/Application.scala

**Comment by balessan** [comment]
Merci, je comprends mieux le truc !

3. Remplacement des liens dans le header par le nom de l'objet + des boutons editer ou cancel contextualisé, fait.
4. en cours, mais probablement besoin qu'on en discute...

**Comment by balessan** [comment]
Considered done (for now) by commit 234a7184f307750e60b50c5af99eb96d16c54a48 and db01057f2ac18531a81d1c4ef3d7c6ec58b7abbe

If more issues related to the edit form, please create new ones.
