### ISSUE TITLE
Pouvoir visualiser la liste de toute les ressources d'un type

### ISSUE THREAD

**Issue by simonLouvet** [jmvanel/semantic_forms#81]
Serait il possible de visualiser toutes les ressource d'un type de manière tabulaire?

**Comment by jmvanel** [comment]
Ca fait l'objet de l'issue #76 .

Pour simplement avoir la liste des resources d'un type (classe) avec leur libellé, il faut aller sur un champ "type" et appuyer sur le bouton "?-->o" .
