### ISSUE TITLE
Improve the login template

### ISSUE THREAD

**Issue by balessan** [jmvanel/semantic_forms#85]
As specified in the template code, may things could be done:

- Splitting into two different templates for login/register (usual strategy in web app development)
- Display/hide the whole login block when willing to create a new account 
- Validate language coherency, currently a french/english mix in labels
- Change the markup of the "Already a member" and  "new user" buttons for H2 ?

Feel free, that's only proposals for now.

**Comment by jmvanel** [comment]
The I18N se fait normalement plutôt via une API dans forms/ ,
exemple d'utilisation:

    I18NMessages.get(m, lang)

et les messages sont dans
src/main/resources/messages/

**Comment by balessan** [comment]
Considered done by commits c9a38f7a51e0e19c6a6e0453ae01f572e168dfaa to 41c1c52efa6acb7104632a0a0573070dccaae531.

Will open a new one related to the first point on the list only.
