### ISSUE TITLE
To be able to visualize an ontology as a graph

### ISSUE THREAD

**Issue by GuillaumeAV** [jmvanel/semantic_forms#88]
Maybe using RDF Viewer, or lodlive ? 

And then, be able to visualize data structured by an ontology ...

**Comment by jmvanel** [comment]
Currently working on OWL documentation by translation into UML:
https://sourceforge.net/p/deductions/code/HEAD/tree/n3_nojs/owl_to_uml.n3

**Comment by jmvanel** [comment]
WebVOWL is integrated
