### ISSUE TITLE
Integrate the PAIR ontology in an instance of semantic forms

### ISSUE THREAD

**Issue by GuillaumeAV** [jmvanel/semantic_forms#89]
And tune the forms ... 

Would be usefull for a presentation during the meetup ;-)

**Comment by jmvanel** [comment]
Seems OK!
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FPerson
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FProject
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Frdfs.org%2Fsioc%2Fns%23Post

TO DO:
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Fwww.virtual-assembly.org%2Fontologies%2F1.0%2Fpair%23Organization
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Fwww.w3.org%2F2002%2F12%2Fcal%2Fical%23Vevent

Make completion within specified class ( here dbo:Species)
http://163.172.179.125:9111/create?uri=&uri=http%3A%2F%2Fdeductions.github.io%2Fbiological-collections.owl.ttl%23Planting

**Comment by jmvanel** [comment]
Today updated the ontologies and form specs in sandbox, by doing:

```bash
source scripts/setClasspath.sh
java -cp $JARS  deductions.runtime.jena.ResetRDFCacheApp
scripts/populateRDFCache.sh
```
