### ISSUE TITLE
View SPARQL select & construct results

### ISSUE THREAD

**Issue by balessan** [jmvanel/semantic_forms#9]
Possibly add FlintSPARQLEditor, but this implies to launch SPARQL HTTP server like Fuseki, or BigData, or to use the SPARQL protocol in the semantic_forms server

**Comment by jmvanel** [comment]
administration tools is certainly a theme for a whole project :)

**Comment by jmvanel** [comment]
Currently we have a very simple tools for CONSTRUCT and SELECT queries;
it's creates HTML on server side;
it's available from the tools pages.

**Comment by jmvanel** [comment]
adding FlintSPARQLEditor , and possibility to download turtle from construct query is desirable, but I close the issue, the feature is here.
