### ISSUE TITLE
Use dbpedia data for search by proximity

### ISSUE THREAD

**Issue by GuillaumeAV** [jmvanel/semantic_forms#98]
Usecase : I'm living in Epinay sur Seine and I'm interested in peer to peer, if someone search for people interested in peer to peer in Ile de France, he should find me ... 

Other stuff : pair ontology uses dcterms:subject, I guess dcterms:subject is connected dbpedia subject ?

**Comment by jmvanel** [comment]
This user story will be covered by #57 ,
plus maybe adding more properties in dbPedia mirror script.
